SELECT ROUND (3.4) FROM DUAL;
SELECT ROUND (3.6) FROM DUAL;
SELECT ROUND (3.5) FROM DUAL;

SELECT CEIL (3.4) FROM DUAL;
SELECT CEIL (3.6) FROM DUAL;
SELECT CEIL (3.5) FROM DUAL;

SELECT POWER (10,4) FROM DUAL;
SELECT POWER (34,4) FROM DUAL;

SELECT SQRT (144) FROM DUAL;
